services:
  - type: web
    name: bingo-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt && chmod +x start.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
